version: '3'
services:
  ros2_dev:
    image: osrf/ros:iron-desktop-full   # Changed to desktop-full
    container_name: ros2_iron_dev
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./src:/ros2_ws/src
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash